// <auto-generated />
using System;
using MiMinimalAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiMinimalAPI.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20240217015305_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiMinimalAPI.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descipcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("a5f81f00-de5d-45ed-be57-29d181d98cd7"),
                            Nombre = "Actividades pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("a5f81f00-de5d-45ed-be57-29d181d98c02"),
                            Nombre = "Actividades personales",
                            Peso = 50
                        });
                });

            modelBuilder.Entity("MiMinimalAPI.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("b4f81f00-de5d-45ed-be57-29d181d98cd7"),
                            CategoriaId = new Guid("a5f81f00-de5d-45ed-be57-29d181d98cd7"),
                            FechaCreacion = new DateTime(2024, 2, 16, 22, 53, 4, 500, DateTimeKind.Local).AddTicks(5570),
                            FechaFinalizacion = new DateTime(2024, 2, 17, 22, 53, 4, 500, DateTimeKind.Local).AddTicks(5583),
                            PrioridadTarea = 1,
                            Titulo = "Pagos de servicios publicos"
                        },
                        new
                        {
                            TareaId = new Guid("b4f81f00-de5d-45ed-be57-29d181d98150"),
                            CategoriaId = new Guid("a5f81f00-de5d-45ed-be57-29d181d98c02"),
                            FechaCreacion = new DateTime(2024, 2, 16, 22, 53, 4, 500, DateTimeKind.Local).AddTicks(5594),
                            FechaFinalizacion = new DateTime(2024, 2, 17, 22, 53, 4, 500, DateTimeKind.Local).AddTicks(5594),
                            PrioridadTarea = 0,
                            Titulo = "Terminar de ver pelicula en netflix"
                        });
                });

            modelBuilder.Entity("MiMinimalAPI.Models.Tarea", b =>
                {
                    b.HasOne("MiMinimalAPI.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MiMinimalAPI.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
